const express = require('express');
const router = express.Router();
const { pool } = require('../config/db');
const jwt = require('jsonwebtoken');
const bcrypt = require('bcryptjs');

function generateSecurePassword() {
  const upper = 'ABCDEFGHJKLMNPQRSTUVWXYZ';
  const lower = 'abcdefghjkmnpqrstuvwxyz';
  const digits = '23456789';
  const special = '!@#$%^&*';
  const all = upper + lower + digits + special;
  const pwd = [
    upper[Math.floor(Math.random() * upper.length)],
    lower[Math.floor(Math.random() * lower.length)],
    digits[Math.floor(Math.random() * digits.length)],
    special[Math.floor(Math.random() * special.length)],
  ];
  for (let i = 4; i < 12; i++) pwd.push(all[Math.floor(Math.random() * all.length)]);
  for (let i = pwd.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [pwd[i], pwd[j]] = [pwd[j], pwd[i]];
  }
  return pwd.join('');
}

// Register
router.post('/register', async (req, res) => {
  console.log(`[REGISTER] POST /api/register`, req.body);
  try {
    const { name, username, phone, email, password } = req.body;
    const phonePattern = /^\+\d{9,15}$/;
    if (!name || !username || !phone) {
      return res.status(400).json({ error: 'Name, username, and phone are required.' });
    }
    if (!phonePattern.test(phone)) {
      return res.status(400).json({ error: 'Phone number must be in format +256771234567.' });
    }
    // Check for existing phone number (check both columns for consistency)
    const [existingPhone] = await pool.execute(
      'SELECT id FROM users WHERE phone = ? OR phone_number = ?',
      [phone, phone]
    );
    if (existingPhone.length > 0) {
      return res.status(400).json({ error: 'Phone number already registered' });
    }
    if (email) {
      const [existing] = await pool.execute('SELECT id FROM users WHERE LOWER(email) = LOWER(?)', [email]);
      if (existing.length > 0) {
        return res.status(400).json({ error: 'Email already registered' });
      }
    }
    const [existingUser] = await pool.execute('SELECT id FROM users WHERE username = ?', [username]);
    if (existingUser.length > 0) {
      return res.status(400).json({ error: 'Username already taken' });
    }

    // Auto-generate password if not provided
    const plainPassword = password || generateSecurePassword();
    const isAutoGenerated = !password;

    const hash = await bcrypt.hash(plainPassword, 10);
    const [insertResult] = await pool.execute(
      'INSERT INTO users (name, username, phone, email, password, created_at) VALUES (?, ?, ?, ?, ?, NOW())',
      [name, username, phone, email || null, hash]
    );
    const userId = insertResult.insertId;
    if (!userId) throw new Error('User insert failed: missing insertId');
    const [rows] = await pool.execute('SELECT id, name, username, phone, email FROM users WHERE id = ?', [userId]);
    const user = rows[0];
    if (!user) return res.status(500).json({ error: 'User not found after insert' });
    const token = jwt.sign({ id: user.id, name: user.name, username: user.username, phone: user.phone, email: user.email }, process.env.JWT_SECRET, { expiresIn: '7d' });
    const response = {
      token,
      user,
      success: true,
      ...(isAutoGenerated && { generatedPassword: plainPassword })
    };
    console.log('[REGISTER] Sending response (password omitted from log)');
    res.status(201).json(response);
  } catch (err) {
    console.error('[REGISTER ERROR]', err);
    if (err && err.stack) {
      console.error('[REGISTER ERROR STACK]', err.stack);
    }
    if (err.message && err.message.includes('Duplicate')) {
      return res.status(400).json({ error: 'User already exists.' });
    }
    res.status(500).json({ error: 'Server error. Please try again.' });
  }
});

// Login - supports email, username, or phone
const authService = require('../services/authService');
router.post('/login', async (req, res) => {
  const { identifier, email: emailField, phone, password } = req.body;
  const email = (identifier || emailField || phone || '').trim();
  console.log('[LOGIN] Incoming login request:', { identifier: email, password: password ? '***' : undefined });
  if (!email || !password) {
    console.warn('[LOGIN] Missing email or password');
    return res.status(400).json({ success: false, error: 'Email/username/phone and password are required' });
  }
  const result = await authService.login({ email, password });
  if (result.success) {
    console.log('[LOGIN] Login successful for:', email);
    res.json(result.data); // Only send { token, user }
  } else {
    console.warn('[LOGIN] Login failed for:', email, '| Reason:', result.error);
    res.status(401).json({ success: false, error: result.error });
  }
});

module.exports = router;

